### ISSUE TITLE
Scraper not getting any data

### ISSUE THREAD

**Issue by henare** [planningalerts-scrapers/ashfield#1]
@CloCkWeRX you had this on the "to be added" list but it's got no data. Do you know what's going on?

**Comment by CloCkWeRX** [comment]
Skip it, will look in to it later tonight

**Comment by CloCkWeRX** [comment]
Ah right; so this is a pretty lonely feed:

http://mycouncil2.solorient.com.au/Horizon/@@horizondap_ashfield@@/atdis/1.0/applications.json?lodgement_date_end=2016-03-22&lodgement_date_start=2016-02-21

Legit 0 items for example in that date range.

I do trust that it works though when there are valid items -

http://mycouncil2.solorient.com.au/Horizon/@@horizondap_ashfield@@/atdis/1.0/applications.json?lodgement_date_end=2016-03-22&lodgement_date_start=2016-02-01

... which is why I marked it as ready to be added

**Comment by henare** [comment]
> I do trust that it works though when there are valid items -
> 
> http://mycouncil2.solorient.com.au/Horizon/@@horizondap_ashfield@@/atdis/1.0/applications.json?lodgement_date_end=2016-03-22&lodgement_date_start=2016-02-01
> 
> ... which is why I marked it as ready to be added

With this kind of work, experience shows that the only way to fully trust is to actually run it, test it, and see the results. This is especially important now we know it's common for these feeds to have bad data.

I'll leave this open until we see some data and can test it properly.

**Comment by CloCkWeRX** [comment]
kk

**Comment by henare** [comment]
Still nothing. I'll assign it back to you to keep an eye out.

**Comment by henare** [comment]
Looks like it's working so I've added it https://www.planningalerts.org.au/authorities/ashfield
